trigger:
    branches:
      include:
        - hotfix/*
  
pool:
  vmImage: "ubuntu-latest"

steps:

  - task: NodeTool@0    
    inputs:
      versionSpec: "12.x"
      
    displayName: "Install Node.js"

  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.1'
      includePrerelease: true
    displayName : "Configurando gitversion"

  - task: gitversion/execute@0
    inputs:
      useConfigFile: false
    displayName: "generando la nueva versión"

 - task: Npm@1
    
    inputs:
      command: "custom"
      customCommand: "--no-git-tag-version version $(MajorMinorPatch)$(PreReleaseTagWithDash)"
    displayName: "actualizando package.json"